services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=studyfactory'
      - 'POSTGRES_PASSWORD=studyfactory'
      - 'POSTGRES_USER=studyfactory'
    ports:
      - '5433:5432'
