-- A reviewed X is workflow state, not an Attendance. Keeping it in a separate
-- table is rollback-safe because previous backend images simply ignore it
-- instead of interpreting it as PRESENT.

BEGIN;

CREATE TABLE IF NOT EXISTS attendance_reviewed_absences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id bigint NOT NULL,
    branch_id bigint NOT NULL,
    attendance_date date NOT NULL,
    slot integer NOT NULL,
    reviewed_by_member_id bigint,
    reviewed_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE attendance_reviewed_absences
    ALTER COLUMN reviewed_by_member_id DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_attendance_reviewed_absences_member_date_slot
    ON attendance_reviewed_absences (member_id, attendance_date, slot);

CREATE INDEX IF NOT EXISTS idx_attendance_reviewed_absences_branch_date
    ON attendance_reviewed_absences (branch_id, attendance_date);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_attendance_reviewed_absences_slot'
          AND conrelid = 'attendance_reviewed_absences'::regclass
    ) THEN
        ALTER TABLE attendance_reviewed_absences
            ADD CONSTRAINT ck_attendance_reviewed_absences_slot
            CHECK (slot BETWEEN 1 AND 7);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_attendance_reviewed_absences_member'
          AND conrelid = 'attendance_reviewed_absences'::regclass
    ) THEN
        ALTER TABLE attendance_reviewed_absences
            ADD CONSTRAINT fk_attendance_reviewed_absences_member
            FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_attendance_reviewed_absences_reviewer'
          AND conrelid = 'attendance_reviewed_absences'::regclass
          AND confdeltype <> 'n'
    ) THEN
        ALTER TABLE attendance_reviewed_absences
            DROP CONSTRAINT fk_attendance_reviewed_absences_reviewer;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_attendance_reviewed_absences_reviewer'
          AND conrelid = 'attendance_reviewed_absences'::regclass
    ) THEN
        ALTER TABLE attendance_reviewed_absences
            ADD CONSTRAINT fk_attendance_reviewed_absences_reviewer
            FOREIGN KEY (reviewed_by_member_id) REFERENCES members (id) ON DELETE SET NULL;
    END IF;
END $$;

-- Heal any reviewed-X rows written by an unreleased intermediate build, then
-- remove them from the legacy table before an older image can read them as O.
DO $$
BEGIN
    IF to_regclass('attendances') IS NOT NULL THEN
        INSERT INTO attendance_reviewed_absences (
            member_id,
            branch_id,
            attendance_date,
            slot,
            reviewed_by_member_id,
            reviewed_at
        )
        SELECT
            attendance.member_id,
            attendance.branch_id,
            attendance.attendance_date,
            attendance.slot,
            reviewer.id,
            attendance.updated_at AT TIME ZONE 'UTC'
        FROM attendances attendance
        JOIN members target ON target.id = attendance.member_id
        LEFT JOIN members reviewer ON reviewer.id = attendance.marked_by_member_id
        WHERE attendance.custom_status_text = 'REVIEWED_ABSENT'
        ON CONFLICT (member_id, attendance_date, slot) DO UPDATE
        SET branch_id = EXCLUDED.branch_id,
            reviewed_by_member_id = EXCLUDED.reviewed_by_member_id,
            reviewed_at = GREATEST(
                attendance_reviewed_absences.reviewed_at,
                EXCLUDED.reviewed_at
            );

        DELETE FROM attendances
        WHERE custom_status_text = 'REVIEWED_ABSENT';
    END IF;
END $$;

COMMIT;
