BEGIN;

ALTER TABLE study_presence_sessions
    ADD COLUMN IF NOT EXISTS automatically_closed boolean;

CREATE TABLE IF NOT EXISTS study_break_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presence_session_id bigint NOT NULL,
    member_id bigint NOT NULL,
    branch_id bigint NOT NULL,
    study_date date NOT NULL,
    study_break varchar(30) NOT NULL,
    window_started_at timestamp(6) with time zone NOT NULL,
    window_ended_at timestamp(6) with time zone NOT NULL,
    started_at timestamp(6) with time zone NOT NULL,
    ended_at timestamp(6) with time zone,
    end_reason varchar(30),
    active_member_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_study_break_sessions_state'
          AND conrelid = 'study_break_sessions'::regclass
    ) THEN
        ALTER TABLE study_break_sessions
            ADD CONSTRAINT ck_study_break_sessions_state CHECK (
                (ended_at IS NULL AND end_reason IS NULL
                    AND active_member_id IS NOT NULL AND active_member_id = member_id)
                OR (ended_at IS NOT NULL AND end_reason IS NOT NULL AND active_member_id IS NULL)
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_study_break_sessions_time'
          AND conrelid = 'study_break_sessions'::regclass
    ) THEN
        ALTER TABLE study_break_sessions
            ADD CONSTRAINT ck_study_break_sessions_time CHECK (
                window_started_at < window_ended_at
                AND started_at >= window_started_at
                AND started_at < window_ended_at
                AND (ended_at IS NULL
                    OR (ended_at >= started_at AND ended_at <= window_ended_at))
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_study_break_sessions_presence'
          AND conrelid = 'study_break_sessions'::regclass
    ) THEN
        ALTER TABLE study_break_sessions
            ADD CONSTRAINT fk_study_break_sessions_presence
            FOREIGN KEY (presence_session_id)
            REFERENCES study_presence_sessions (id)
            ON DELETE RESTRICT;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_study_break_sessions_active_member
    ON study_break_sessions (active_member_id);

CREATE INDEX IF NOT EXISTS idx_study_break_sessions_member_date_started
    ON study_break_sessions (member_id, study_date, started_at);

CREATE INDEX IF NOT EXISTS idx_study_break_sessions_branch_date_started
    ON study_break_sessions (branch_id, study_date, started_at);

CREATE INDEX IF NOT EXISTS idx_study_break_sessions_presence_started
    ON study_break_sessions (presence_session_id, started_at);

CREATE INDEX IF NOT EXISTS idx_study_break_sessions_active_window_end
    ON study_break_sessions (active_member_id, window_ended_at);

COMMIT;
