-- Preserve one beverage-preference lifecycle even when its replaceable item
-- rows are recreated or the member saves an empty preference. Timestamps are
-- UTC instants so the Staff client can classify the Seoul business date.

BEGIN;

CREATE TABLE IF NOT EXISTS beverage_preference_audits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_beverage_preference_audits_member
    ON beverage_preference_audits (member_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_beverage_preference_audits_member'
          AND conrelid = 'beverage_preference_audits'::regclass
    ) THEN
        ALTER TABLE beverage_preference_audits
            ADD CONSTRAINT fk_beverage_preference_audits_member
            FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE;
    END IF;
END $$;

-- Production item timestamps were stored as UTC LocalDateTime values. Recover
-- the best available lifecycle for preferences created before this migration.
DO $$
BEGIN
    IF to_regclass('beverage_items') IS NOT NULL THEN
        INSERT INTO beverage_preference_audits (member_id, created_at, updated_at)
        SELECT
            items.member_id,
            MIN(items.created_at AT TIME ZONE 'UTC'),
            MAX(items.updated_at AT TIME ZONE 'UTC')
        FROM beverage_items items
        JOIN members member ON member.id = items.member_id
        GROUP BY items.member_id
        ON CONFLICT (member_id) DO UPDATE
        SET created_at = LEAST(beverage_preference_audits.created_at, EXCLUDED.created_at),
            updated_at = GREATEST(beverage_preference_audits.updated_at, EXCLUDED.updated_at);
    END IF;
END $$;

-- Some installations still retain the original preference table. It can
-- recover the initial timestamp even if the current item rows were replaced.
DO $$
BEGIN
    IF to_regclass('beverage_preferences') IS NOT NULL
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = current_schema()
             AND table_name = 'beverage_preferences'
             AND column_name = 'created_at'
       )
       AND EXISTS (
           SELECT 1 FROM information_schema.columns
           WHERE table_schema = current_schema()
             AND table_name = 'beverage_preferences'
             AND column_name = 'updated_at'
       ) THEN
        INSERT INTO beverage_preference_audits (member_id, created_at, updated_at)
        SELECT
            preference.member_id,
            MIN(preference.created_at AT TIME ZONE 'UTC'),
            MAX(preference.updated_at AT TIME ZONE 'UTC')
        FROM beverage_preferences preference
        JOIN members member ON member.id = preference.member_id
        GROUP BY preference.member_id
        ON CONFLICT (member_id) DO UPDATE
        SET created_at = LEAST(beverage_preference_audits.created_at, EXCLUDED.created_at),
            updated_at = GREATEST(beverage_preference_audits.updated_at, EXCLUDED.updated_at);
    END IF;
END $$;

-- Migrations run before the container swap and a failed deploy may restore the
-- previous backend. This trigger lets those older images keep the lifecycle
-- accurate without needing to know this table exists, including delete-to-empty.
CREATE OR REPLACE FUNCTION touch_beverage_preference_audit_from_item()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_member_id bigint;
    changed_at timestamp(6) with time zone;
BEGIN
    IF TG_OP = 'DELETE' THEN
        affected_member_id := OLD.member_id;
    ELSE
        affected_member_id := NEW.member_id;
    END IF;
    changed_at := clock_timestamp();

    -- Legacy beverage rows can outlive a deleted member. They must not block
    -- application startup or cleanup by attempting to create an orphan audit.
    IF NOT EXISTS (SELECT 1 FROM members WHERE id = affected_member_id) THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;

    INSERT INTO beverage_preference_audits (member_id, created_at, updated_at)
    VALUES (affected_member_id, changed_at, changed_at)
    ON CONFLICT (member_id) DO UPDATE
    SET updated_at = GREATEST(beverage_preference_audits.updated_at, EXCLUDED.updated_at);

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DO $$
BEGIN
    IF to_regclass('beverage_items') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_beverage_items_preference_audit ON beverage_items;
        CREATE TRIGGER trg_beverage_items_preference_audit
            AFTER INSERT OR DELETE ON beverage_items
            FOR EACH ROW
            EXECUTE FUNCTION touch_beverage_preference_audit_from_item();
    END IF;
END $$;

COMMIT;
