BEGIN;

CREATE TABLE IF NOT EXISTS study_presence_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id bigint NOT NULL,
    branch_id bigint NOT NULL,
    checked_in_at timestamp(6) with time zone NOT NULL,
    checked_out_at timestamp(6) with time zone,
    close_reason varchar(30),
    active_member_id bigint,
    closed_by_member_id bigint,
    automatically_closed boolean,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE study_presence_sessions
    ADD COLUMN IF NOT EXISTS closed_by_member_id bigint;

ALTER TABLE study_presence_sessions
    ADD COLUMN IF NOT EXISTS automatically_closed boolean;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_study_presence_sessions_state'
          AND conrelid = 'study_presence_sessions'::regclass
    ) THEN
        ALTER TABLE study_presence_sessions
            ADD CONSTRAINT ck_study_presence_sessions_state CHECK (
                (checked_out_at IS NULL AND close_reason IS NULL
                    AND active_member_id IS NOT NULL AND active_member_id = member_id)
                OR (checked_out_at IS NOT NULL AND close_reason IS NOT NULL
                    AND active_member_id IS NULL)
            );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_study_presence_sessions_time'
          AND conrelid = 'study_presence_sessions'::regclass
    ) THEN
        ALTER TABLE study_presence_sessions
            ADD CONSTRAINT ck_study_presence_sessions_time CHECK (
                checked_out_at IS NULL OR checked_out_at >= checked_in_at
            );
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_study_presence_sessions_active_member
    ON study_presence_sessions (active_member_id);

CREATE INDEX IF NOT EXISTS idx_study_presence_sessions_member_checked_in
    ON study_presence_sessions (member_id, checked_in_at);

CREATE INDEX IF NOT EXISTS idx_study_presence_sessions_branch_checked_in
    ON study_presence_sessions (branch_id, checked_in_at);

COMMIT;
