-- Seed the built-in attendance statuses before the backend begins serving.
-- This removes first-request create races across concurrent manager updates.

BEGIN;

CREATE TABLE IF NOT EXISTS attendance_status_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    custom_allowed boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

-- Heal any duplicate names created by the former first-request check/save
-- path before enforcing the invariant. Existing Attendance rows keep pointing
-- at the oldest canonical status row.
DO $$
BEGIN
    IF to_regclass('attendances') IS NOT NULL THEN
        UPDATE attendances attendance
        SET attendance_status_type_id = canonical.id
        FROM attendance_status_types duplicate
        JOIN (
            SELECT name, MIN(id) AS id
            FROM attendance_status_types
            GROUP BY name
        ) canonical ON canonical.name = duplicate.name
        WHERE attendance.attendance_status_type_id = duplicate.id
          AND duplicate.id <> canonical.id;
    END IF;
END $$;

DELETE FROM attendance_status_types duplicate
USING attendance_status_types canonical
WHERE duplicate.name = canonical.name
  AND duplicate.id > canonical.id;

CREATE UNIQUE INDEX IF NOT EXISTS uk_attendance_status_types_name
    ON attendance_status_types (name);

INSERT INTO attendance_status_types (name, custom_allowed, created_at, updated_at)
VALUES ('출석', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (name) DO NOTHING;

COMMIT;
